import Head from 'next/head';
import Layout from '../components/Layout';
import Image from 'next/image';
import devPic from '../../public/images/profile/developer-pic-1.png'
import AnimatedText from '@/components/AnimatedText';
import Link from 'next/link'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className='flex items-center text-dark w-full min-h-screen'>
        <Layout className='pt-0'>
          <div className='flex items-center justify-between w-full'>
            <div className='w-1/2'>
              <Image src={devPic} alt="Developer Image" className='w-full h-auto'/>
            </div>
            <div className='w-1/2 flex flex-col items-center self-center'>
              <AnimatedText text="Crafting Beautiful and Intuitive Web Experiences" className='!text-6xl !text-left'/>
              <p className='my4 text-base font-medium'>
                Highly motivated web developer with expertise in designing and developing user interfaces. Skilled in creating UI pages and debugging web applications. Possesses exceptional analytical and problem-solving skills in a fast-paced environment. Proficient in front-end and back-end frameworks, with a passion for staying up-to-date with emerging technologies.
              </p>
              <div>
                <Link href="https://sapphire-celinda-59.tiiny.site/" target={"_blank"}>
                  Resume
                </Link>
                <Link href="mailto:hubertyang88@yahoo.com" target={"_blank"}>Contact</Link>
              </div>
            </div>
          </div>
        </Layout>
      </main>
    </>
  )
}
